// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uobiniyocextyhtfrvfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvYmluaXlvY2V4dHlodGZydmZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NDQ4NjEsImV4cCI6MjA1ODUyMDg2MX0.bys-HmQr4CcevCFGPjiAwjUDD0IHMPKPFq5UM4XqsYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);